In [1]:
import numpy as np 
import pandas as pd 
from pandas.plotting import register_matplotlib_converters
%matplotlib inline

import seaborn as sns
sns.set_style("darkgrid")

import matplotlib.pyplot as plt
from collections import Counter

from pylab import rcParams
plt.rcParams['figure.figsize'] = (12,12)
plt.rcParams['figure.dpi'] = 400

import warnings
warnings.filterwarnings("ignore")
warnings.warn("this will not show")

pd.set_option('display.max_columns', None)

In [2]:
df0 = pd.read_csv("IMDB.csv")
df = df0.copy()

In [3]:
df.head()

,Unnamed: 0,Name of movie,Year of relase,Watchtime,Movie Rating,Metascore,Votes,Gross collection,Description,Director,Star
0,0,Jai Bhim,2021,164,9.3,Nan,"173,295",#139,When a tribal man is arrested for a case of al...,T.J. Gnanavel,"['Suriya', 'Lijo Mol Jose', 'Manikandan', 'Raj..."
1,1,The Shawshank Redemption,1994,142,9.3,80,"2,541,091",$28.34M,Two imprisoned men bond over a number of years...,Frank Darabont,"['Tim Robbins', 'Morgan Freeman', 'Bob Gunton'..."
2,2,The Godfather,1972,175,9.2,100,"1,748,410",$134.97M,The aging patriarch of an organized crime dyna...,Francis Ford Coppola,"['Marlon Brando', 'Al Pacino', 'James Caan', '..."
3,3,Soorarai Pottru,2020,153,9.1,Nan,"107,159",Nan,"Nedumaaran Rajangam ""Maara"" sets out to make t...",Sudha Kongara,"['Suriya', 'Paresh Rawal', 'Aparna Balamurali'..."
4,4,The Dark Knight,2008,152,9.0,84,"2,491,371",$534.86M,When the menace known as the Joker wreaks havo...,Christopher Nolan,"['Christian Bale', 'Heath Ledger', 'Aaron Eckh..."

In [4]:
df.shape

(1000, 11)

In [5]:
df.describe()

        Unnamed: 0    Watchtime  Movie Rating
count  1000.000000  1000.000000   1000.000000
mean    499.500000   136.910000      8.552000
std     288.819436    27.486677      0.218045
min       0.000000    87.000000      8.300000
25%     249.750000   116.000000      8.400000
50%     499.500000   134.500000      8.500000
75%     749.250000   155.250000      8.600000
max     999.000000   207.000000      9.300000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        1000 non-null   int64
 1   Name of movie     1000 non-null   object
 2   Year of relase    1000 non-null   object
 3   Watchtime         1000 non-null   int64
 4   Movie Rating      1000 non-null   float64
 5   Metascore         1000 non-null   object
 6   Votes             1000 non-null   object
 7   Gross collection  1000 non-null   object
 8   Description       1000 non-null   object
 9   Director          1000 non-null   object
 10  Star              1000 non-null   object
dtypes: float64(1), int64(2), object(8)
memory usage: 86.1+ KB

In [7]:
df.Watchtime.max()

207

In [8]:
df.iloc[df.Watchtime.argmax()]

Unnamed: 0                                                         36
Name of movie                                    Shichinin no samurai
Year of relase                                                   1954
Watchtime                                                         207
Movie Rating                                                      8.6
Metascore                                                          98
Votes                                                         335,289
Gross collection                                               $0.27M
Description         A poor village under attack by bandits recruit...
Director                                               Akira Kurosawa
Star                ['Toshirô Mifune', 'Takashi Shimura', 'Keiko T...
Name: 36, dtype: object

In [9]:
df[~df["Year of relase"].str.isdigit()]

,Unnamed: 0,Name of movie,Year of relase,Watchtime,Movie Rating,Metascore,Votes,Gross collection,Description,Director,Star
38,38,96,II 2018,158,8.5,Nan,"27,527",Nan,Two high school sweethearts meet at a reunion ...,C. Prem Kumar,"['Vijay Sethupathi', 'Adithya Bhaskar', 'Trish..."
61,61,Joker,I 2019,122,8.4,59,"1,140,433",$335.45M,"In Gotham City, mentally troubled comedian Art...",Todd Phillips,"['Joaquin Phoenix', 'Robert De Niro', 'Zazie B..."
69,69,Coco,I 2017,105,8.4,81,"460,262",$209.73M,"Aspiring musician Miguel, confronted with his ...","Directors:Lee Unkrich, Adrian Molina","['Anthony Gonzalez', 'Gael García Bernal', 'Be..."
138,138,96,II 2018,158,8.5,Nan,"27,527",Nan,Two high school sweethearts meet at a reunion ...,C. Prem Kumar,"['Vijay Sethupathi', 'Adithya Bhaskar', 'Trish..."
161,161,Joker,I 2019,122,8.4,59,"1,140,433",$335.45M,"In Gotham City, mentally troubled comedian Art...",Todd Phillips,"['Joaquin Phoenix', 'Robert De Niro', 'Zazie B..."
169,169,Coco,I 2017,105,8.4,81,"460,262",$209.73M,"Aspiring musician Miguel, confronted with his ...","Directors:Lee Unkrich, Adrian Molina","['Anthony Gonzalez', 'Gael García Bernal', 'Be..."
238,238,96,II 2018,158,8.5,Nan,"27,527",Nan,Two high school sweethearts meet at a reunion ...,C. Prem Kumar,"['Vijay Sethupathi', 'Adithya Bhaskar', 'Trish..."
261,261,Joker,I 2019,122,8.4,59,"1,140,433",$335.45M,"In Gotham City, mentally troubled comedian Art...",Todd Phillips,"['Joaquin Phoenix', 'Robert De Niro', 'Zazie B..."
269,269,Coco,I 2017,105,8.4,81,"460,262",$209.73M,"Aspiring musician Miguel, confronted with his ...","Directors:Lee Unkrich, Adrian Molina","['Anthony Gonzalez', 'Gael García Bernal', 'Be..."
338,338,96,II 2018,158,8.5,Nan,"27,527",Nan,Two high school sweethearts meet at a reunion ...,C. Prem Kumar,"['Vijay Sethupathi', 'Adithya Bhaskar', 'Trish..."
361,361,Joker,I 2019,122,8.4,59,"1,140,433",$335.45M,"In Gotham City, mentally troubled comedian Art...",Todd Phillips,"['Joaquin Phoenix', 'Robert De Niro', 'Zazie B..."
369,369,Coco,I 2017,105,8.4,81,"460,262",$209.73M,"Aspiring musician Miguel, confronted with his ...","Directors:Lee Unkrich, Adrian Molina","['Anthony Gonzalez', 'Gael García Bernal', 'Be..."
438,438,96,II 2018,158,8.5,Nan,"27,527",Nan,Two high school sweethearts meet at a reunion ...,C. Prem Kumar,"['Vijay Sethupathi', 'Adithya Bhaskar', 'Trish..."
461,461,Joker,I 2019,122,8.4,59,"1,140,433",$335.45M,"In Gotham City, mentally troubled comedian Art...",Todd Phillips,"['Joaquin Phoenix', 'Robert De Niro', 'Zazie B..."
469,469,Coco,I 2017,105,8.4,81,"460,262",$209.73M,"Aspiring musician Miguel, confronted with his ...","Directors:Lee Unkrich, Adrian Molina","['Anthony Gonzalez', 'Gael García Bernal', 'Be..."
538,538,96,II 2018,158,8.5,Nan,"27,527",Nan,Two high school sweethearts meet at a reunion ...,C. Prem Kumar,"['Vijay Sethupathi', 'Adithya Bhaskar', 'Trish..."
561,561,Joker,I 2019,122,8.4,59,"1,140,433",$335.45M,"In Gotham City, mentally troubled comedian Art...",Todd Phillips,"['Joaquin Phoenix', 'Robert De Niro', 'Zazie B..."
569,569,Coco,I 2017,105,8.4,81,"460,262",$209.73M,"Aspiring musician Miguel, confronted with his ...","Directors:Lee Unkrich, Adrian Molina","['Anthony Gonzalez', 'Gael García Bernal', 'Be..."
638,638,96,II 2018,158,8.5,Nan,"27,527",Nan,Two high school sweethearts meet at a reunion ...,C. Prem Kumar,"['Vijay Sethupathi', 'Adithya Bhaskar', 'Trish..."
661,661,Joker,I 2019,122,8.4,59,"1,140,433",$335.45M,"In Gotham City, mentally troubled comedian Art...",Todd Phillips,"['Joaquin Phoenix', 'Robert De Niro', 'Zazie B..."
669,669,Coco,I 2017,105,8.4,81,"460,262",$209.73M,"Aspiring musician Miguel, confronted with his ...","Directors:Lee Unkrich, Adrian Molina","['Anthony Gonzalez', 'Gael García Bernal', 'Be..."
738,738,96,II 2018,158,8.5,Nan,"27,527",Nan,Two high school sweethearts meet at a reunion ...,C. Prem Kumar,"['Vijay Sethupathi', 'Adithya Bhaskar', 'Trish..."
761,761,Joker,I 2019,122,8.4,59,"1,140,433",$335.45M,"In Gotham City, mentally troubled comedian Art...",Todd Phillips,"['Joaquin Phoenix', 'Robert De Niro', 'Zazie B..."
769,769,Coco,I 2017,105,8.4,81,"460,262",$209.73M,"Aspiring musician Miguel, confronted with his ...","Directors:Lee Unkrich, Adrian Molina","['Anthony Gonzalez', 'Gael García Bernal', 'Be..."
838,838,96,II 2018,158,8.5,Nan,"27,527",Nan,Two high school sweethearts meet at a reunion ...,C. Prem Kumar,"['Vijay Sethupathi', 'Adithya Bhaskar', 'Trish..."
861,861,Joker,I 2019,122,8.4,59,"1,140,433",$335.45M,"In Gotham City, mentally troubled comedian Art...",Todd Phillips,"['Joaquin Phoenix', 'Robert De Niro', 'Zazie B..."
869,869,Coco,I 2017,105,8.4,81,"460,262",$209.73M,"Aspiring musician Miguel, confronted with his ...","Directors:Lee Unkrich, Adrian Molina","['Anthony Gonzalez', 'Gael García Bernal', 'Be..."
938,938,96,II 2018,158,8.5,Nan,"27,527",Nan,Two high school sweethearts meet at a reunion ...,C. Prem Kumar,"['Vijay Sethupathi', 'Adithya Bhaskar', 'Trish..."
961,961,Joker,I 2019,122,8.4,59,"1,140,433",$335.45M,"In Gotham City, mentally troubled comedian Art...",Todd Phillips,"['Joaquin Phoenix', 'Robert De Niro', 'Zazie B..."
969,969,Coco,I 2017,105,8.4,81,"460,262",$209.73M,"Aspiring musician Miguel, confronted with his ...","Directors:Lee Unkrich, Adrian Molina","['Anthony Gonzalez', 'Gael García Bernal', 'Be..."

In [10]:
import re

In [11]:
re.sub("[^0-9]", "", "sdkjh987978asd098as0980a98sd")

'987978098098098'

In [12]:
df["Year of relase"] = df["Year of relase"].str.extract('(^\d*)')

In [13]:
df[~df["Year of relase"].str.isdigit()]

,Unnamed: 0,Name of movie,Year of relase,Watchtime,Movie Rating,Metascore,Votes,Gross collection,Description,Director,Star
38,38,96,,158,8.5,Nan,"27,527",Nan,Two high school sweethearts meet at a reunion ...,C. Prem Kumar,"['Vijay Sethupathi', 'Adithya Bhaskar', 'Trish..."
61,61,Joker,,122,8.4,59,"1,140,433",$335.45M,"In Gotham City, mentally troubled comedian Art...",Todd Phillips,"['Joaquin Phoenix', 'Robert De Niro', 'Zazie B..."
69,69,Coco,,105,8.4,81,"460,262",$209.73M,"Aspiring musician Miguel, confronted with his ...","Directors:Lee Unkrich, Adrian Molina","['Anthony Gonzalez', 'Gael García Bernal', 'Be..."
138,138,96,,158,8.5,Nan,"27,527",Nan,Two high school sweethearts meet at a reunion ...,C. Prem Kumar,"['Vijay Sethupathi', 'Adithya Bhaskar', 'Trish..."
161,161,Joker,,122,8.4,59,"1,140,433",$335.45M,"In Gotham City, mentally troubled comedian Art...",Todd Phillips,"['Joaquin Phoenix', 'Robert De Niro', 'Zazie B..."
169,169,Coco,,105,8.4,81,"460,262",$209.73M,"Aspiring musician Miguel, confronted with his ...","Directors:Lee Unkrich, Adrian Molina","['Anthony Gonzalez', 'Gael García Bernal', 'Be..."
238,238,96,,158,8.5,Nan,"27,527",Nan,Two high school sweethearts meet at a reunion ...,C. Prem Kumar,"['Vijay Sethupathi', 'Adithya Bhaskar', 'Trish..."
261,261,Joker,,122,8.4,59,"1,140,433",$335.45M,"In Gotham City, mentally troubled comedian Art...",Todd Phillips,"['Joaquin Phoenix', 'Robert De Niro', 'Zazie B..."
269,269,Coco,,105,8.4,81,"460,262",$209.73M,"Aspiring musician Miguel, confronted with his ...","Directors:Lee Unkrich, Adrian Molina","['Anthony Gonzalez', 'Gael García Bernal', 'Be..."
338,338,96,,158,8.5,Nan,"27,527",Nan,Two high school sweethearts meet at a reunion ...,C. Prem Kumar,"['Vijay Sethupathi', 'Adithya Bhaskar', 'Trish..."
361,361,Joker,,122,8.4,59,"1,140,433",$335.45M,"In Gotham City, mentally troubled comedian Art...",Todd Phillips,"['Joaquin Phoenix', 'Robert De Niro', 'Zazie B..."
369,369,Coco,,105,8.4,81,"460,262",$209.73M,"Aspiring musician Miguel, confronted with his ...","Directors:Lee Unkrich, Adrian Molina","['Anthony Gonzalez', 'Gael García Bernal', 'Be..."
438,438,96,,158,8.5,Nan,"27,527",Nan,Two high school sweethearts meet at a reunion ...,C. Prem Kumar,"['Vijay Sethupathi', 'Adithya Bhaskar', 'Trish..."
461,461,Joker,,122,8.4,59,"1,140,433",$335.45M,"In Gotham City, mentally troubled comedian Art...",Todd Phillips,"['Joaquin Phoenix', 'Robert De Niro', 'Zazie B..."
469,469,Coco,,105,8.4,81,"460,262",$209.73M,"Aspiring musician Miguel, confronted with his ...","Directors:Lee Unkrich, Adrian Molina","['Anthony Gonzalez', 'Gael García Bernal', 'Be..."
538,538,96,,158,8.5,Nan,"27,527",Nan,Two high school sweethearts meet at a reunion ...,C. Prem Kumar,"['Vijay Sethupathi', 'Adithya Bhaskar', 'Trish..."
561,561,Joker,,122,8.4,59,"1,140,433",$335.45M,"In Gotham City, mentally troubled comedian Art...",Todd Phillips,"['Joaquin Phoenix', 'Robert De Niro', 'Zazie B..."
569,569,Coco,,105,8.4,81,"460,262",$209.73M,"Aspiring musician Miguel, confronted with his ...","Directors:Lee Unkrich, Adrian Molina","['Anthony Gonzalez', 'Gael García Bernal', 'Be..."
638,638,96,,158,8.5,Nan,"27,527",Nan,Two high school sweethearts meet at a reunion ...,C. Prem Kumar,"['Vijay Sethupathi', 'Adithya Bhaskar', 'Trish..."
661,661,Joker,,122,8.4,59,"1,140,433",$335.45M,"In Gotham City, mentally troubled comedian Art...",Todd Phillips,"['Joaquin Phoenix', 'Robert De Niro', 'Zazie B..."
669,669,Coco,,105,8.4,81,"460,262",$209.73M,"Aspiring musician Miguel, confronted with his ...","Directors:Lee Unkrich, Adrian Molina","['Anthony Gonzalez', 'Gael García Bernal', 'Be..."
738,738,96,,158,8.5,Nan,"27,527",Nan,Two high school sweethearts meet at a reunion ...,C. Prem Kumar,"['Vijay Sethupathi', 'Adithya Bhaskar', 'Trish..."
761,761,Joker,,122,8.4,59,"1,140,433",$335.45M,"In Gotham City, mentally troubled comedian Art...",Todd Phillips,"['Joaquin Phoenix', 'Robert De Niro', 'Zazie B..."
769,769,Coco,,105,8.4,81,"460,262",$209.73M,"Aspiring musician Miguel, confronted with his ...","Directors:Lee Unkrich, Adrian Molina","['Anthony Gonzalez', 'Gael García Bernal', 'Be..."
838,838,96,,158,8.5,Nan,"27,527",Nan,Two high school sweethearts meet at a reunion ...,C. Prem Kumar,"['Vijay Sethupathi', 'Adithya Bhaskar', 'Trish..."
861,861,Joker,,122,8.4,59,"1,140,433",$335.45M,"In Gotham City, mentally troubled comedian Art...",Todd Phillips,"['Joaquin Phoenix', 'Robert De Niro', 'Zazie B..."
869,869,Coco,,105,8.4,81,"460,262",$209.73M,"Aspiring musician Miguel, confronted with his ...","Directors:Lee Unkrich, Adrian Molina","['Anthony Gonzalez', 'Gael García Bernal', 'Be..."
938,938,96,,158,8.5,Nan,"27,527",Nan,Two high school sweethearts meet at a reunion ...,C. Prem Kumar,"['Vijay Sethupathi', 'Adithya Bhaskar', 'Trish..."
961,961,Joker,,122,8.4,59,"1,140,433",$335.45M,"In Gotham City, mentally troubled comedian Art...",Todd Phillips,"['Joaquin Phoenix', 'Robert De Niro', 'Zazie B..."
969,969,Coco,,105,8.4,81,"460,262",$209.73M,"Aspiring musician Miguel, confronted with his ...","Directors:Lee Unkrich, Adrian Molina","['Anthony Gonzalez', 'Gael García Bernal', 'Be..."

In [14]:
df["Year of relase"]=df["Year of relase"].str.replace("I ","").str.replace("I","")
df["Year of relase"]

0      2021
1      1994
2      1972
3      2020
4      2008
       ...
995    2017
996    2013
997    2012
998    2011
999    2010
Name: Year of relase, Length: 1000, dtype: object

In [16]:
df["Year of relase"] = pd.to_numeric(df["Year of relase"])
df

,Unnamed: 0,Name of movie,Year of relase,Watchtime,Movie Rating,Metascore,Votes,Gross collection,Description,Director,Star
0,0,Jai Bhim,2021.0,164,9.3,Nan,"173,295",#139,When a tribal man is arrested for a case of al...,T.J. Gnanavel,"['Suriya', 'Lijo Mol Jose', 'Manikandan', 'Raj..."
1,1,The Shawshank Redemption,1994.0,142,9.3,80,"2,541,091",$28.34M,Two imprisoned men bond over a number of years...,Frank Darabont,"['Tim Robbins', 'Morgan Freeman', 'Bob Gunton'..."
2,2,The Godfather,1972.0,175,9.2,100,"1,748,410",$134.97M,The aging patriarch of an organized crime dyna...,Francis Ford Coppola,"['Marlon Brando', 'Al Pacino', 'James Caan', '..."
3,3,Soorarai Pottru,2020.0,153,9.1,Nan,"107,159",Nan,"Nedumaaran Rajangam ""Maara"" sets out to make t...",Sudha Kongara,"['Suriya', 'Paresh Rawal', 'Aparna Balamurali'..."
4,4,The Dark Knight,2008.0,152,9.0,84,"2,491,371",$534.86M,When the menace known as the Joker wreaks havo...,Christopher Nolan,"['Christian Bale', 'Heath Ledger', 'Aaron Eckh..."
...,...,...,...,...,...,...,...,...,...,...,...
995,995,Vikram Vedha,2017.0,147,8.3,Nan,"35,901",Nan,"Vikram, a no-nonsense police officer, accompan...","Directors:Gayatri, Pushkar","['Madhavan', 'Vijay Sethupathi', 'Shraddha Sri..."
996,996,Drishyam,2013.0,160,8.3,Nan,"39,570",#244,A man goes to extreme lengths to save his fami...,Jeethu Joseph,"['Mohanlal', 'Meena', 'Asha Sharath', 'Ansiba']"
997,997,Jagten,2012.0,115,8.3,77,"313,647",$0.69M,"A teacher lives a lonely life, all the while s...",Thomas Vinterberg,"['Mads Mikkelsen', 'Thomas Bo Larsen', 'Annika..."
998,998,Jodaeiye Nader az Simin,2011.0,123,8.3,95,"238,130",$7.10M,A married couple are faced with a difficult de...,Asghar Farhadi,"['Payman Maadi', 'Leila Hatami', 'Sareh Bayat'..."
999,999,Incendies,2010.0,131,8.3,80,"168,727",$6.86M,Twins journey to the Middle East to discover t...,Denis Villeneuve,"['Lubna Azabal', 'Mélissa Désormeaux-Poulin', ..."

In [17]:
df= df.drop(['Unnamed: 0'], axis=1)

In [18]:
df.head()

,Name of movie,Year of relase,Watchtime,Movie Rating,Metascore,Votes,Gross collection,Description,Director,Star
0,Jai Bhim,2021.0,164,9.3,Nan,"173,295",#139,When a tribal man is arrested for a case of al...,T.J. Gnanavel,"['Suriya', 'Lijo Mol Jose', 'Manikandan', 'Raj..."
1,The Shawshank Redemption,1994.0,142,9.3,80,"2,541,091",$28.34M,Two imprisoned men bond over a number of years...,Frank Darabont,"['Tim Robbins', 'Morgan Freeman', 'Bob Gunton'..."
2,The Godfather,1972.0,175,9.2,100,"1,748,410",$134.97M,The aging patriarch of an organized crime dyna...,Francis Ford Coppola,"['Marlon Brando', 'Al Pacino', 'James Caan', '..."
3,Soorarai Pottru,2020.0,153,9.1,Nan,"107,159",Nan,"Nedumaaran Rajangam ""Maara"" sets out to make t...",Sudha Kongara,"['Suriya', 'Paresh Rawal', 'Aparna Balamurali'..."
4,The Dark Knight,2008.0,152,9.0,84,"2,491,371",$534.86M,When the menace known as the Joker wreaks havo...,Christopher Nolan,"['Christian Bale', 'Heath Ledger', 'Aaron Eckh..."